version: '3.7'

services:
  app:
    container_name: golden_fin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    env_file:
      - app/.env
    stdin_open: true
    tty: true