# Generated by Django 3.2.3 on 2021-05-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetails',
            name='loan_amortization',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='loandetails',
            name='loan_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
